language: ruby

rvm:
  - 2.2.2

services:
  - mysql
  - redis-server

before_script:
  - sudo echo -e 'innodb_large_prefix=on' >> /etc/my.cnf
  - cp config/database.travis.yml config/database.yml

script:
  - export RACK_ENV=test
  - rake db:setup
  - rake test
