production:
  adapter: mysql
  hostname: "localhost"
  port: 3306
  user: "root"
  password: ""
  database: "hashview"
  # encoding: "ISO-8859-1"

development:
  adapter: mysql
  hostname: "localhost"
  port: 3306
  user: "root"
  password: ""
  database: "hashview_dev"
  #encoding: "ISO-8859-1"

test:
  adapter: mysql
  hostname: "localhost"
  port: 3306
  user: "root"
  password: ""
  database: "hashview_test"
  # encoding: "ISO-8859-1"